/* Agregar datos a las tablas de la base de datos */
USE recetas;

/* Tabla usuarios */
INSERT INTO usuarios (nombre, apellidos, dni, e_mail, contrasena) VALUES ('Julio', 'Pillado Castillo', '45846607V', 'jpillado84@gmail.com', MD5('abc123.'));
INSERT INTO usuarios (nombre, apellidos, dni, e_mail, contrasena) VALUES ('Javier', 'Gonzalez Blanco', '11111111A', 'jgonzalez@gmail.com', MD5('abc123.'));
INSERT INTO usuarios (nombre, apellidos, dni, e_mail, contrasena) VALUES ('Maria', 'Calvo Castro', '22222222B', 'mcalvo@gmail.com', MD5('abc123.'));
INSERT INTO usuarios (nombre, apellidos, dni, e_mail, contrasena) VALUES ('Juana', 'De Arco', '33333333C', 'jdearco@gmail.com', MD5('abc123.'));
INSERT INTO usuarios (nombre, apellidos, dni, e_mail, contrasena) VALUES ('Pedro', 'Ximenez Coto', '44444444D', 'pximenez@gmail.com', MD5('abc123.'));
INSERT INTO usuarios (nombre, apellidos, dni, e_mail, contrasena) VALUES ('Mario', 'Bros', '55555555E', 'mbros@gmail.com', MD5('abc123.'));
INSERT INTO usuarios (nombre, apellidos, dni, e_mail, contrasena) VALUES ('Marco', 'Polo', '66666666F', 'mpolo@gmail.com', MD5('abc123.'));
INSERT INTO usuarios (nombre, apellidos, dni, e_mail, contrasena) VALUES ('Luis', 'Gutierrez Mendez', '77777777G', 'lgutierrez@gmail.com', MD5('abc123.'));
INSERT INTO usuarios (nombre, apellidos, dni, e_mail, contrasena) VALUES ('Miguel', 'Porro', '88888888H', 'mporro@gmail.com', MD5('abc123.'));
INSERT INTO usuarios (nombre, apellidos, dni, e_mail, contrasena) VALUES ('Marta', 'Sanchez Pizjuán', '99999999I', 'msanchez@gmail.com', MD5('abc123.'));

/* Tabla tipos */
INSERT INTO tipo (nombre) VALUES ('Postres');
INSERT INTO tipo (nombre) VALUES ('Tapas');
INSERT INTO tipo (nombre) VALUES ('Cóctel');
INSERT INTO tipo (nombre) VALUES ('Comidas');
INSERT INTO tipo (nombre) VALUES ('Desayunos');
INSERT INTO tipo (nombre) VALUES ('Bocadillos');

/* Tabla recetas */
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('1', '4', 'Espaguetis a la carbonara', 'No utilices bacon o bacon ahumado para hacer esta receta. Busca el auténtico guanciale italiano, hecho con la papada del cerdo y si no, utiliza en su lugar una buena panceta fresca, retirando la piel. Córtala en trocitos de pequeño tamaño y fríe esos trocitos hasta que comiencen a dorarse.

Por otro lado bate las 3 yemas de huevo con el huevo y el queso pecorino recién rallado hasta hacer una mezcla algo espesa. Dale unos toques de pimienta negra a esa mezcla. Entre tanto, pon la pasta a cocer en agua abundante con sal, y sácala cuando falten un par de minutos para que esté al dente.

En la sartén donde habíamos reservado la panceta o el guanciale salteado, agregaremos la pasta escurrida a la que añadimos la mezcla de huevos, queso y pimienta, mezclando bien. Agregamos también un cucharón del agua de cocción de la pasta.

Removemos mientras se van integrando los distintos ingredientes y se va haciendo una especie de salsa al cuajar ligeramente el huevo con el caldo caliente de la cocción. Servimos espolvoreando de un poco más de pecorino rallado y dando un par de vueltas más de pimienta molida.', 'Yemas de huevo 3, Huevo 1, Panceta (Mejor si es Guanciale) 100g, Queso Pecorino 50g, Espaguetis 320g, Pimienta negra molida al gusto, Sal, Agua');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('1', '1', 'Tarta Selva negra', 'Elaboración de la placa de bizcocho

Ponemos un bol al baño maría y en él batimos los huevos junto con el azúcar hasta que este a una temperatura tibia, retiramos el bol del baño maría y seguimos batiendo hasta que tenga un aspecto cremoso y haya doblado su volumen.

Tamizamos la harina junto con la fécula y el cacao, lo mezclamos todo y lo vamos incorporando poco a poco a la mezcla anterior removiendo suavemente con una espátula.

Por último agregamos la mantequilla derretida poco a poco removiendo también con una espátula.

Disponemos una placa para horno , le colocamos un papel vegetal encima y vertemos la masa sobre el, con la ayuda de una espátula o una paleta lisa, vamos esparciendo la masa por la bandeja de manera que nos quede 1 cm. de espesor mas o menos. Tiene que quedarnos una placa fina.

Cocemos 30 min. a 190º. ( como siempre digo…dependiendo del horno, hay que controlarlo) Retiramos del horno, desmoldamos con cuidado y reservamos.
Para la crema de chocolate

En un cazo al fuego hervimos la leche junto con el azúcar, añadimos el chocolate a trocitos, mezclamos bien para que se incorpore.

Mezclamos la fécula con un poco de leche para que no tenga grumos, lo incorporamos a la leche que tenemos en el fuego, removemos hasta que se convierta en una crema. Retiramos del fuego y dejamos enfriar.

Con unas varillas eléctricas batimos la mantequilla hasta conseguir una textura cremosa, se la añadimos a la mezcla anterior. Que ya estará fría La introducimos en una manga pastelera con boquilla lisa y la guardamos en el frigorífico.
Para la crema de nata

Montamos muy firme la nata con el azúcar. La introducimos en una manga pastelera con boquilla lisa y guardamos también en el frigorífico.
Montaje de la selva negra

Cortamos la placa de bizcocho que hemos elaborado al principio y la cortamos en tres partes iguales, en la primera le ponemos la crema de chocolate con la manga pastelera, colocamos con cuidado la segunda placa encima y sobre ella ponemos la crema de nata, acabamos con la tercera placa que nos queda.

*Si la vamos a dejar entera, la guardamos en el frigorífico hasta la hora de servir. Si queremos tenerla en porciones individuales para luego no tener que cortarla, la metemos en el congelador un par de horas., para que no se nos rompa al cortarla ya que es de textura suave y frágil.

Cuando este congelada, la cortamos en porciones individuales de la forma que queráis, redondas, cuadradas o rectangulares como estas. Antes de servir espolvoreáis con azúcar glas y como más os guste, en este caso un poco de ganache y unas tejas de chocolate. Os saldrán unas 8 porcinaes más o menos.', '7 Huevos frescos., 370 g. Azúcar, 300 g. Mantequilla, 150 g. Harina, 70 g Fécula Maíz, 50 g Cacao en polvo, 80 g Chocolate de cobertura, 250 g Leche, 250 g Nata para montar, Azúcar glas, Tejas de chocolate o ganache de chocolate');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('1', '3', '', 'Empezaremos por el procedimiento básico, aunque luego os haré unas cuantas anotaciones después, ya para nota. Lo primero es añadir unas dos cucharaditas de azúcar en un vaso alto y un poco ancho (aunque también vale de tubo), sobre el azúcar se añade media lima troceada, y se exprime con la ayuda del mortero.

Sobre el azúcar añadimos un golpe de sifón, más o menos el doble de la cantidad que vayamos a poner de ron (en el vídeo se puede ver claramente), y es ahora cuando se añade la hierbabuena, que machacamos, pero sin llegar a picarla, simplemente para liberar su aroma. Después añadimos el ron blanco, y por último el hielo. Removemos, colocamos la correspondiente pajita, decoramos con una ramita de hierbabuena y listo.', 'Ron blanco, Sifón o agua con gas, Hierbabuena, Azúcar, Lima, Hielo');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('1', '2', 'Mini quiches de cebolla caramelizada, pera y romero', 'Precalentar el horno a 190ºC con ventilador, o 200ºC con calor arriba y abajo. Engrasar ligeramente con aceite o mantequilla el molde, solo si no es antiadherente. Lavar y secar el romero y la pera. Sacar unas hojitas de romero y picarlas finas. Pelar la pera y cortarla en cubitos pequeños.

Estirar el hojaldre sin dejarlo muy fino y recortar círculos con un cortapastas o un vaso, que sean más grandes que las cavidades del molde. Forrar los huecos procurando que no haya burbujas de aire. No tiene por qué quedar perfecto, se puede reajustar la masa moldeando con los dedos. Cortar el sobrante y guardar para otra elaboración en la nevera.

Repartir la cebolla caramelizada en el fondo de cada tartita y rellenar con trocitos de pera y queso picado o desmenuzado, añadiendo una pequeña porción de romero. Batir en un cuenco el huevo con la nata y la mostaza, salpimentar y aderezar con nuez moscada. Cubrir las quiches con la mezclar y hornear durante unos 12-15 minutos en la mitad inferior del horno.', 'Hojaldre rectangular refrigerado 1, Cebolla caramelizada (unas 6 cucharadas) 90g, Queso Brie o camembert, o similar 80g, Pera conferencia grande o similar 1, Huevo L 1, Nata líquida para cocinar 200ml, Mostaza de Dijon (opcional) 10ml, Romero fresco, Pimienta negra molida, Nuez moscada molida (opcional)');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('1', '6', 'Bocadillo de calamares', 'Limpiamos el calamar y separamos las aletas y tentáculos. El cuerpo lo cortamos en anillas con un cuchillo afilado. Las aletas son algo más duras por lo que las usaremos para guisos.

Mezclamos las harinas y pasamos los calamares para enharinarlos. Es importante eliminar el exceso, sacudiendo los calamares sobre un colador. Calentamos abundante aceite de oliva a unos 180ºC, para que el rebozado quede crujiente. Freímos hasta que estén bien dorados.

Los retiramos con espumadera y escurrimos sobre papel absorbente. Repartimos sobre los panes generosamente, abiertos previamente por la mitad. Opcionalmente se puede añadir mayonesa o zumo de limón.', 'Calamar fresco pequeño 1, Harina de garbanzo 50g, Harina de trigo común 50g, Pan baguette o panecillos para bocadillos 2, Aceite de oliva virgen extra, Sal');

INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('2', '3', 'Bloody Mary', 'A la hora de condimentar este cóctel, es fundamental un buen toque de salsa Perrins, muy poco Tabasco (dos gotas) para no pasarnos de picante agresivo y dos o tres vueltas de pimienta negra que completarán el efecto picante, para que quede en su punto. Opcionalmente se puede añadir un chorrito de caldo concentrado de carne para potenciar el sabor. Agregamos también el zumo de limón, aproximadamente 15 ml y agitamos con un cubo de hielo para mezclar bien y enfriar. Continuamos con el vodka, utilizando la medida del jigger pequeño o grande, en función de la proporción de alcohol que se desee incorporar. Lo habitual es utilizar una tercera parte de la cantidad de zumo de tomate que se vaya a usar. Para 210 ml de tomate, utilizaremos 70 ml de vodka y la proporción quedará en su punto. No obstante, con la experiencia de Kike el lo hace a ojo (y lo clava). Para incorporar el apio y la sal, el barman nos recomienda utilizar sal de apio, que aporta el inconfundible sabor de la hortaliza, sin saturar (evitando de paso que su sabor nos pueda repetir). Además así incorporamos el toque salado. No obstante, para terminar la preparación, vamos a meter una ramita de apio dentro del vaso dejando que asome por fuera que servirá para remover nuestro Bloody Mary, como si fuera una cucharilla. Ya sólo falta el zumo de tomate y agitar para que esté en su punto. El barman de Soda 917 nos recomienda airear bien el Bloody Mary, lanzándolo desde la coctelera al vaso dos o tres veces para terminar sirviéndolo en la copa, finalizando con la ramita de apio fresco. En caso de añadir hielo, hay que hacerlo al terminar de servir, sin echar más de dos cubitos para que nuestro Bloody Mary no quede aguado. ', 'Vodka 70ml, Zumo de tomate 210ml, Zumo de limón, Salsa Tabasco dos gotas, Salsa Worcestershire tres gotas, Pimienta negra molida, Apio');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('2', '1', 'Trufas de cava y frambuesa', 'Calentamos la nata junto al azúcar hasta que hierva. En un cuenco troceamos el chocolate y vertemos la nata caliente por encima mientras removemos con unas varillas para que el chocolate se deshaga completamente. Agregamos la mantequilla y el cava mezclamos totalmente. Vertemos la mezcla en una bandeja, echamos la frambuesa, removemos y refrigeramos hasta que la masa se haya endurecido (cuanta más delgada sea la superficie antes se enfría). Una vez tengamos la masa cuajada, hacemos bolitas de igual tamaño con una cuchara y damos forma de bolita perfecta con las manos, teniendo cuidado de no dar mucho calor a la masa. Por último rebozamos cada trufa en lo que prefiramos: cacao en polvo, virutas, bolitas de anís, etc. Refrigeramos hasta el momento de tomar en un recipiente hermético o túper para que el chocolate no se humedezca.', 'Chocolate negro 70% de cacao 100g, Nata líquida 80ml, Cava 30ml, Azúcar glasé 25g, Mantequilla 5g, Frambuesas deshidratadas 25g, Cacao puro en polvo');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('2', '1', 'Tarta rápida de chocolate negro y galletas Oreo', 'Empezamos pulverizando las galletas Oreo con la ayuda de un robot de cocina. Las mezclamos con la mantequilla derretida, hasta obtener una pasta con la que forraremos la base y parte de las paredes del molde. Lo metemos en el congelador mientras preparamos el relleno.

Ponemos la nata en un cazo y la calentamos sin que llegue a hervir. La retiramos del fuego y añadimos el chocolate y la mantequilla, removiendo con unas varillas para que se deshaga el chocolate. Cuando esté todo integrado, vertemos esta crema sobre la base de galletas reservada.

Por último, decoramos la superficie de la tarta al gusto y guardamos en la nevera hasta el momento de servir. ', 'Galletas Oreo 200g, Mantequilla reblandecida 100g, Chocolate negro 70% de cacao 200g, Nata líquida para montar 200g, Mantequilla 25g, Fideos de chocolate para decorar');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('2', '4', 'Tortilla de patatas', 'Pela y pica la cebolla en dados medianos. Limpia el pimiento verde, retírale el tallo y las pepitas y córtalo en dados.

Si las patatas estuvieran sucias, pásalas por agua. Pélalas, córtalas por la mitad a lo largo y después corta cada trozo en medias lunas finas de 1/2 centímetros.

Introduce todo en la sartén, sazona a tu gusto y fríe a fuego suave durante 25-30 minutos.

Retira la fritada y escúrrela. Pasa el aceite a un recipiente y resérvalo. Limpia la sartén con papel absorbente de cocina.

Casca los huevos, colócalos en un recipiente grande y bátelos. Sálalos a tu gusto, agrega la fritada de patatas, cebolla y pimiento y mezcla bien.

Coloca la sartén nuevamente en el fuego, agrega un chorrito del aceite reservado y agrega la mezcla. Remueve un poco con una cuchara de madera y espera (20 segundos) a que empiece a cuajarse.

Separa los bordes, cubre la sartén con un plato de mayor diámetro que la sartén y dale la vuelta.

Échala de nuevo para que cuaje por el otro lado.', '6 huevos, 1 cebolla pequeña, 2 vasos de aceite de oliva, 3 patatas (600 gr), 1 pimiento verde, sal, una hoja de perejil');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('2', '5', 'Tortitas de avena con plátano', 'Casca el huevo en un bol y bátelo junto con el azúcar. Añade la leche y mezcla. Tamiza encima la harina con la levadura, la canela y una pizca de sal. Pela los plátanos. Aplasta uno de ellos con un tenedor y añádelo al bol. Aromatiza con la vainilla. Bate hasta conseguir una crema homogénea. Calienta 1 cucharada de mantequilla en una sartén antiadherente pequeña y cuaja la masa anterior en forma de tortitas. Cuécelas 2 minutos por cada lado. Retíralas y resérvalas. Limpia las fresas, lávalas y córtalas con el plátano restante en rodajas. Reparte las tortitas en los platos intercalando tortitas y capas de fruta. Vierte la miel por encima y sirve.', '5 cucharadas de harina de avena, 100 g de fresas, 75 ml de leche vegetal, 2 cucharadas de miel, ½ cucharadita de levadura, 2 cucharadas de azúcar moreno, canela, 1 huevo, 2 plátanos, sal, ½ cucharadita de esencia de vainilla, mantequilla');

INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('3', '2', 'Empanadillas de jamón y queso', '
Preparamos el relleno de las empanadillas doblando cada lóncha de jamón de York y cortándola con la forma escogida con ayuda de un cortapastas o un cortador de galletas. Yo he elegido uno con forma de estrella. Repetimos la operación con las lonchas de queso. Los recortes tanto del queso como del jamón, son estupendos para hacer sándwiches mixtos o para alegrar una ensalada de lechuga y tomate, ya sabéis que no nos gusta tirar nada. En una bandeja de horno, disponemos cuatro obleas de empanadillas y sobre ellas colocamos el relleno -las estrellas de jamón y queso-. Cubrimos con otras cuatro obleas aplastando bien para marcar la forma de estrella y hacemos un repulgue o cierre pellizcando y doblando el exceso hasta dar la vuelta a toda la empanadilla. Asamos las empanadillas en el horno a 190º C tras barnizarlas con huevo batido, sacándolas cuando están doradas. Las servimos como aperitivo -una por persona es suficiente- o para una cena -dos o tres en ese caso- acompañadas de una ensalada verde de mezcla de lechugas.', 'Empanadillas (obleas) 8, Jamón de York lonchas 2, Queso de sandwich lonchas 4, Huevo 1');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('3', '4', 'Callos a la madrileña', 'Los callos a la madrileña se hacen normalmente utilizando varios tipos de carne de la casquería. Así entre sus ingredientes encontramos callos de ternera, pata y morro. En la casquería podemos pedir un kilo de callos indicando que queremos ese peso repartido entre los tres ingredientes. Limpiamos bien los callos y los cortamos en trozos cuadrados de 2x2 cm aproximadamente, para que después de su cocción puedan ser tamaño bocado.

Una vez limpios, los ponemos a cocer con una hoja de laurel y un buen puñado de sal, agregando también la panceta o carne de jamón o lacón y las especias para callos. Dejamos que los callos se hagan durante 4 horas en cacerola tradicional o 45 minutos si usáis olla rápida. Una vez estén cocinados, los escurrimos y reservamos el agua de la cocción que será espesa y cargada de gelatina..

Cuando falte una hora para terminar la cocción tradicional, agregamos el chorizo y la morcilla, que habremos semicocido aparte. Al integrarlos ahora, dejando que se terminen de hacer con los demás ingredientes evitaremos que se reviente la morcilla o que la receta nos quedase demasiado cargada de la grasa del chorizo.

Preparamos una salsa pochando dos dientes de ajo con la cebolla muy picada y una guindilla para que los callos tengan un puntito picante. Entonces agregamos una cucharada de salsa de tomate, los callos cocidos, los chorizos y morcillas troceados. También vamos incorporando poco a poco, el caldo de la cocción. Terminamos dejando hervir el conjunto durante 20 minutos hasta que adquiera cremosidad y llegue a una textura deseada.', 'Callos de ternera 1kg, Chorizo asturiano, Morcilla de cebolla, Panceta 150g, Laurel, Mezcla especias para callos al gusto al gusto, Dientes de ajo 2, Guindilla al gusto, Salsa de tomate 50ml');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('3', '2', 'Pimientos rellenos de salmón, aguacate y cangrejo', 'Para poder desmigar el salmón noruego, lo hacemos a la plancha a fuego lento sin usar nada de aceite. En un par de minutos por cada lado, quedará en su punto. Luego quitamos la piel y lo desmigamos con un cuchillo.

Por otro lado cortamos el aguacate en trocitos pequeños y deshacemos los palitos de surimi de cangrejo convirtiéndolos en hilos. En un bol, ponemos los tres ingredientes y añadimos una cucharada sopera de mayonesa, mezclando hasta conseguir una masa más o menos homogénea.

Abrimos la lata de pimientos del piquillo y los pasamos por la sartén un minuto por cada cara, lo justo para que no estén crudos. Cuando se enfrían, los rellenamos con la farsa preparada. Si se nos rompe alguno lo guardamos para dar un toque a la salsa.

Para hacer la salsa, usamos la batidora y trituramos el yogur con dos cucharadas soperas de mayonesa y uno o dos pimientos hasta conseguir una salsa ligera de color rosado. Montamos el plato colocando los pimientos añadiendo la salsa por la zona del pico y espolvoreando con cebollino muy picado.', 'Pimientos del piquillo 15, Yogur natural 1, Mayonesa 3 cucharadas, Palitos de cangrejo (surimi) 150g, Salmón fresco 150g, Aguacate (medio)');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('3', '4', 'Ensalada de alubias blancas con aguacate', 'Lavar los tomates, secar y cortar en gajos. Pelar el aguacate, partir por la mitad, retirar el hueso y trocear la pulpa (añadir un chorrito de limón por encima para evitar la oxidación). Trocear las aceitunas negras. En un tarro mezclar aceite de oliva virgen extra, vinagre, una pizca de sal y pimienta. Remover con un tenedor hasta emulsionar la vinagreta.

Escurrir las alubias, mezclar con las aceitunas, aguacate, tomate, perejil y aliñar con la vinagreta. Espolvorear con perejil picado por encima.

Si queréis preparar un plato único con esta ensalada podéis combinarlo con alguna conserva de pescado, como unos filetes de melva, atún o con sardinas, como en la imagen ¡veréis qué delicia!', '400 g de alubias blancas cocidas (pueden ser de bote), 2 tomates, 1 aguacate, 60 g aceitunas negras, 4 cucharadas de aceite de oliva virgen extra, 4 cucharadas de vinagre, Sal, Pimienta, Perejil');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('3', '4', 'Ensaladilla rusa', 'Pon las patatas (limpia y con piel) a cocer a fuego suave en una cazuela con agua fría. Pela las zanahorias y añádelas. Déjalas cocer (patatas y zanahorias) durante 25 minutos. A los 25 minutos de cocción,introduce los huevos, 1 cucharada de sal y deja cocer durante 10 minutos más.

Escurre el agua, deja que se temple todo. Reserva las zanahorias en un plato y pela las patatas y el huevo.

Pica la patata y el huevo en daditos. Corta las zanahorias en 4 cuartos a lo largo. Apila los trozos y córtalas perpendicularmente hasta conseguir trocitos pequeños.

Corta las aceitunas por la mitad y después finamente.

Pon la patata, el huevo, la zanahoria y las aceitunas en un cuenco grande, agrega los guisantes y el atún desmigado.Incorpora la mayonesa, mezcla suavemente. Prueba, pon a punto de sal y sirve. Adorna con una rama de perejil.

Consejo:

En esta ocasión, no hemos añadido vinagre al agua de cocción de las patatas porque, como es para preparar una ensaladilla, no importa que las patatas se rompan en la cocción.', '2-3 patatas (450 g), 4 zanahorias, 2 huevos, 20 aceitunas rellenas, 3 cucharadas de guisantes en conserva, 2 latas de atún en aceite (200 g), 2/4 de mayonesa casera, sal, perejil');

INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('4', '1', 'Mug cake de chocolate en microondas', 'Disponer la mantequilla troceada en un cuenco apto para microondas con el cacao tamizado, el sirope y la leche. Calentar en el microondas a máxima potencia 30 segundos y remover bien para mezclar todo. Si aún estuviera la mantequilla algo sólida, calentar de nuevo en intervalos de 10 segundos.

Añadir el huevo, la vainilla, la sal y la almendra, mezclando con varillas o tenedor hasta homogeneizar. Incorporar el chocolate negro picado o en chips, mezclar suavemente y repartir en dos tazas engrasadas ligeramente con mantequilla. Deben estar llenas hasta no más de la mitad.

Calentar ambas a la vez en el microondas durante 1 minuto y 20 segundos en potencia máxima. Pinchar con un palillo en el centro; debería salir ligeramente manchado, pero no chorreando masa cruda. Volver a calentar en intervalos de 10 segundos si se prefiere más hecho.', 'Mantequilla y un poco más para engrasar 40g, Cacao en polvo 10g, Sirope de arce o ágave o dátil 30ml, Leche o bebida vegetal 60ml, Huevo 1, Esencia de vainilla 5ml, Sal 1g, Almendra molida 40g, Levadura química (una pizca, opcional) 1g, Chocolate negro o chips 20g');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('4', '4', 'Espaguetis de calabacín con gambas', 'Con un sacapuntas (de cocina), saca los espaguetis de calabacín. Ponlos en un colador, sazona y deja que escurran durante 10-15 minutos.

Pela las gambas, córtalas en 3 trozos y resérvalas. Coloca las cabezas en un cazo con 100 ml de aceite de oliva virgen extra y ponlo al fuego. Cuando empiece a hervir retira la cazuela del fuego, deja que se temple un poco y pon todo en un vaso batidor. Tritura con la batidora eléctrica, cuela y reserva el jugo.

Limpia los ajos frescos, córtalos en 3 trozos, sazona y saltéalos en una sartén con un chorrito de aceite.

Pela y lamina el diente de ajo. Calienta un wok sartén con un chorrito de aceite, agrega el ajo, la media cayena y las gambas. Sazona, saltéalas brevemente y retíralas a un plato. Añade los espaguetis y saltéalos a fuego fuerte.

Sirve los espaguetis de calabacín, coloca encima las gambas y los ajos frescos. Salséalos con el jugo de gambas.

Sirve y decora con una hoja de perejil.', '1/2 calabacín, 1 diente de ajo, 1/2 cayena, 8 gambas, 8 ajos frescos, 150 ml de aceite de oliva virgen extra, sal, perejil');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('4', '1', 'Brownie', 'Pesamos y preparamos todos los ingredientes de ambas elaboraciones, galletas por un lado y brownie por otro, para que el proceso sea más rápido una vez arranquemos. Forramos un molde de unos 30x20 cm con papel vegetal y encendemos el horno, con calor arriba y abajo, a 170 ºC.

Para la base de galleta mezclamos la mantequilla y el azúcar, removiendo bien hasta integrar. Incorporamos la yema de huevo y la esencia de vainilla. Removemos de nuevo. A continuación agregamos la harina y la levadura y mezclamos bien. Terminamos con los chips de chocolate.

Cuando todos los ingredientes estén bien integrados, introducimos la mezcla en el congelador unos minutos, para que coja cuerpo, y nos ponemos a preparar la mezcla del brownie.

Batimos el aceite de oliva y el azúcar en un cuenco. Añadimos los huevos y el chocolate, previamente fundido (ya sea al baño maría o en el microondas). Removemos hasta incorporar. A continuación agregamos la harina y el cacao, tamizados, y un pellizco de sal. Cuando la mezcla esté homogénea añadimos las chips de chocolate.

Retiramos la masa de galleta del congelador y la volcamos en la fuente. Extendemos bien, pero sin aplastar. Cubrimos con la masa del brownie, procurando que cubra bien toda la superficie. Cocemos en el horno durante 30 minutos. Retiramos y dejamos enfriar antes de consumir.

Recomendamos dejar reposar unas horas (mejor de un día para otro) para que adquiera cuerpo, sabor y se asienten las masas. Si optamos por ello deberemos cubrir el molde con papel film o introducirlo en una bolsa de plástico.', 'Mantequilla (para la base de galleta) 100g, Azúcar moreno (para la base de galleta) 90g, Yema de huevo L (para la base de galleta) 1, Esencia de vainilla (para la base de galleta) 3ml, Harina de trigo (para la base de galleta) 110g, Levadura química (para la base de galleta) 3g, Chips de chocolate (para la base de galleta) 75g, Aceite de oliva suave (para la capa de brownie) 90ml, Azúcar (para la capa de brownie) 175g, Huevo L (para la capa de brownie) 2, Chocolate negro para postres (para la capa de brownie) 125g, Harina de trigo (para la capa de brownie) 70g, Cacao en polvo (para la capa de brownie) 15g, Sal una pizca (para la capa de brownie), Chips de chocolate (para la capa de brownie) 80g');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('4', '5', 'Chocolate a la taza casero', 'Para preparar el chocolate a la taza, pon a calentar la leche en una cazuela. Trocea el chocolate y añádelo. Si lo deseas, añade también la rama de canela para aromatizarlo.

Remueve y cuando empiece a hervir, retira del fuego. Cuando el chocolate deje de burbujear, ponlo de nuevo al fuego hasta que comience a hervir (esta operación se hace para que quede más denso).

Cocina removiendo hasta que el chocolate quede completamente disuelto y con una textura ligera.

Consejo:

Si te gusta el chocolate más espeso, debes cocinarlo durante más tiempo. Otra opción es añadir una cucharada de harina de maíz refinada al chocolate mientras se cocina.

Un truco:

Puedes servir el chocolate caliente cubierto de nata montada, una presentación muy habitual. Además, puedes espolvorear un poco de canela molida por encima para darle un toque especial.', '400 gr de chocolate de cobertura, 1 l de leche, ');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('4', '3', 'Tom Collins', 'Vierte en el vaso el zumo de un limón (aproximadamente 100 ml), una cucharada de azúcar o sirope, dos medidas de ginebra y, finalmente, la soda (te cabra medio botellín). Remueve bien para que se diluya el azúcar. Añade tres o cuatro o cubitos de huelo y una rodaja de limón y a disfrutar.', '50 ml de ginebra, 100 ml de zumo de limón, 100 ml de soda, 1 cucharada de azúcar, hielo');

INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('5', '1', 'Muffins de tarta de zanahoria', 'Mientras el horno se calienta a 180º solo debemos ir mezclando los ingredientes en un bol grande. Primero batimos enérgicamente tres huevos. Luego añadimos un yogur griego y removemos otra vez, hasta que se mezcle por completo. Añadimos ahora unos 170 g de sirope de arce, una cucharadita de extracto de vainilla y 60 ml de leche. Seguimos mezclando.

Ahora añadimos dos zanahorias peladas y ralladas, 200 g de harina de trigo integral, un sobre de levadura química y una cucharadita de canela molida. Ahora, con ayuda de una espátula, remueve todo, solo para que esté mezclado.

Con ayuda de una cuchara, rellena una fuente de horno para magdalenas (o moldes de magdalenas individuales). Hornea la mezcla entre 20 y 30 minutos, hasta que las tartas se eleven.

Mientras, preparamos la cobertura de las tartas mezclando 225 gramos de queso crema, 85 g de sirope de arce, y una cucharadita de extraco de vainilla. Para esto mejor usar una batidora de varillas.

Una vez que las minitartas se hayan enfriado, las cubrimos con la cobertura y están listas para sorprender a nuestros invitados.', 'Huevos 1, Yogur griego 1, Sirope de arce 255g, Leche entera 60ml, Extracto de vainilla cucharaditas 2, Zanahoria 2, Harina de trigo integral 200g, Levadura química sobre 1, Canela molida cucharadita 1, Queso crema 225g');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('5', '2', 'Chorizo al vino', 'Poner una cazuela al fuego y añadr los chorizos enteros, ligeramente pinchados. Dejar que empiecen a soltar aroma sin tostarse mucho, añadir las hierbas, apartar del fuego y cubrir con el vino y el agua.

Llevar a ebullición, tapar, bajar el fuego y dejar cocer suavemente durante unos 30-40 minutos, removiendo de vez en cuando.

Sacar con cuidado cada chorizo, cortar en rodajas no muy finas y devolver a la cazuela. Dejar reposar unos pocos minutos antes de servir, en la misma cazuela o en otra fuente, mejor de barro.', 'Chorizo oreado o similar fresco 4, Hierbas provenzales o laurel 5g, Vino blanco 200ml, Agua 50ml');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('5', '5', 'Tortitas de manzana', '
    Cascar los huevos separando las claras de las yemas. En un recipiente mezclar la harina, el azúcar, el azúcar con aroma de vainilla, la canela, las yemas, la leche y la pizca de sal. Batirlo todo muy bien.
    Pelar las manzanas y, quitándoles el corazón, rallarlas. Mezclar con la masa.
    Poner a calentar un poco de aceite o mantequilla en una sartén pequeña a fuego medio-alto.
    Echar medio cacito de la masa en la sartén para que quede con forma redondeada y esponjosa.
    Darle la vuelta a los 2 minutos y dejar que se haga un minuto más por el otro lado. Repetir el proceso con cada tortita.
    Si quieres que tengan más sabor a manzana puedes poner un gajo de manzana una vez pongas la masa en la sartén.
', '2 manzanas, 200 g de harina, 2 huevos, 140 g de azúcar, 1 vaso de leche, 1 cucharada de azúcar con aroma de vainilla, 1 pizca de sal, 1 pizca de canela, Aceite o mantequilla');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('5', '6', 'Bocadillo de ternera con salteado de pimiento, cebolla y mozzarella', 'Salpimentar y aderezar la carne con tomillo y orégano; reservar. Calentar un poco de aceite en una sartén y añadir la cebolla con una pizca de sal. Cocinar a fuego medio-bajo hasta que se caramelice al gusto. Añadir el pimiento y saltear a temperatura media hasta que esté tierno o dejándolo con un punto crujiente. Retirar. Cortar la porción de pan y abrir en dos mitades. Cocinar la carne a la plancha o parrilla procurando que quede al punto. Retirar. Abrir el pan y dorar en la misma parrilla. Presionar para compactarlo un poco. Montar el bocadillo con una base de tomate salpimentado, la carne, la mezcla de verduras y el queso. Dar un golpe de pimienta y añadir orégano al gusto. Cerrar y pasar por la parrilla de nuevo', '1 cebolla dulce o blanca en juliana fina, 1 pimiento rojo en tiras, 2 filetes de ternera pequeños, 1 tomate en rama en rodajas, rodajas de mozzarella fresca, orégano, tomillo, pimienta negra, sal y aceite de oliva virgen extra, pan de chapata o similar');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('5', '6', 'Bocadillo de tinga de pollo al chile chipotle', 'Sofreímos la cebolla y el tomate con aceite. Dejamos a fuego lento mientras en una olla tendremos la pechuga de pollo hirviendo por unos 20 minutos. Al terminar este tiempo retiramos el pollo del agua y la deshebramos. Agregamos el pollo a la sartén. Picamos el chile y lo añadimos. Sazonamos con el comino, sal y pimienta. Revolvemos bien todo y dejamos a fuego lento unos 10 a 12 minutos. Calentamos los panes miniatura, los cortamos en dos y rellenamos con la tinga', '250 g de cebolla blanca en juliana, 1 tomate maduro en trozos, 1 pechuga de pollo, 4 panecillos tiernos, 1 chile chipotle en adobo, 2 g de comino molido, sal, pimienta negra y aceite de oliva virgen extra');

INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('6', '6', 'Pulled pork', 'Marinamos la carne

En un recipiente mezclamos todos los ingredientes con 2 o 3 cucharadas de agua, las que sirvan para lograr una pasta cremosa. Con esta pasta pincelamos toda la pieza de carne y la ponemos dentro de un recipiente con tapa dentro de la nevera, lo ideal es de un día para el otro, pero por lo menos 4 horas. Nosotros solemos hacerlo por la noche para cocinar el pulled pork al día siguiente.
Cocemos la carne

Cuando tengamos la carne bien marinada, vamos a proceder con la cocción. En la olla rápida (como esta) calentamos 2 cucharadas de aceite a fuego medio. Cuando esté caliente incorporamos la carne y la marcamos por todos sus lados, es decir que la carne tiene que cambiar de color en todas las caras, para sellar los jugos.

Una vez que la carne está marcada, incorporamos el caldo de carne o pollo, la cebolla troceada y el agua necesaria para cubrir por completo la pieza de carne. Cerramos la olla con la tapa, y cuando salgan las dos anillas rojas, bajamos un poco el fuego y dejamos cocinar 50 minutos. Pasado este tiempo, retiramos la olla del fuego y esperamos a que la válvula haya bajado del todo antes de abrir.
Preparamos el pulled pork con salsa barbacoa

Una vez que podemos abrir la olla rápida, retiramos la carne y la desmenuzamos, usando un cuchillo o incluso las manos. Es un trabajito que lleva algo de tiempo, pero cuanto mejor la desmiguemos más sabrosa e impregnada de la salsa quedará luego. Mientras desmigamos la carne, ponemos la olla con el caldo de la cocción que ha quedado al fuego medio-alto, para que se reduzca un poco.

En una sartén amplia ponemos la carne desmenuzada, el caldo de la cocción que ya se habrá espesado un poco, y cocinamos a fuego medio-alto unos 5 minutos. Incorporamos la salsa barbacoa, removemos y dejamos que coja todo sabor 3 o 4 minutos más. Retiramos del fuego y ya tenemos listo nuestro pulled pork.', '1.5 kg de carne de cerdo en una sola pieza. Escoge una carne con grasa como la paleta el cuello o la aguja, 350 g de salsa barbacoa, 1 cebolla, 1 litro de caldo de carne o pollo, aceite de oliva, pimentón dulce, canela, comino, ajo en polvo, pimienta negra, salsa Worcestershire, tomillo seco, sal, 2 cucharadas de azúcar moreno, 2-3 cucharadas de agua');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('6', '6', 'La metralleta belga', 'Empezamos preparando la carne. Limpiamos bien una pechuga, la cortamos en tiras y estas a su vez en dados del mismo grosor. En Bruselas te ponen la metralleta con diferentes tipos de carne: en hamburguesa, desmigada, empanada, en bistec... De cerdo, de ternera o pollo. Yo voy a hacer mi propia versión. En un táper echamos un par de cucharadas de aceite de oliva virgen extra y un par de cucharaditas generosas de especias para pinchitos, sino tenéis podéis echar curry. Mezclamos bien hasta conseguir una pasta. Salamos ligeramente la pechuga y removemos. La incorporamos al táper y mezclamos para que todos los trozos de pollo se impregnen bien. Tapamos bien y reservamos en la nevera un mínimo de una hora (yo recomiendo dejarla 12 horas).

Preparamos la "Salsa andaluza" típica belga, En un bol echamos 3-4 cucharadas soperas de mayonesa, incorporamos un cubito de tomate concentrado, y mezclamos bien. A continuación echamos la ralladura de 1/2 limón, un puñado de perejil fresco picado, 1 cucharada de cebolleta picada y 1 guindilla o chile bien picado. Mezclamos y reservamos en la nevera.

Pelamos un par de patatas, una por persona o por bocadillo en este caso. Las lavamos, las cortamos en bastones no muy finos y los echamos en un bol con agua fría. Mientras, en una sartén cocinamos el pollo, no es necesario añadirle nada de aceite, con el que tiene del marinado es suficiente. Una vez cocinado lo reservamos en un plato hasta el momento de preparar el bocadillo. Secamos muy bien las patatas con papel de cocina. En una sartén echamos abundante aceite de oliva virgen extra. Cocinamos a fuego medio las patatas, lo que queremos conseguir es que queden tiernas por dentro y ligeramente crujientes por fuera. Una vez tiernas subimos el fuego a máxima potencia para que se doren. Sacamos sobre papel de cocina, para que suelten el exceso de aceite. Salamos.

Ya tenemos todo preparado para montar nuestra metralleta. Sobre media baguette abierta echamos la carne. A continuación echamos la cebolla caramelizada, un par de hojas de lechuga bien crujientes y una buena cantidad de patatas. Rematamos nuestro bocadillo con la salsa andaluza y un par de pinchos, porque si no nos comemos primero algunas patatas, es imposible cerrar el bocadillo.', '1 baguette, 1 pechuga de pollo, 2 cucharaditas de especias para pinchitos, 2 patatas (variedad Kennebec o agrias), Lechuga, 1 cebolla, Aceite de oliva virgen extra, Sal, 3-4 cucharadas de mayonesa, 1 cubito de tomate concentrado, 1 cucharada de cebolleta picada, Perejil fresco picado, 1 chile o guindilla, Ralladura de 1/2 limon');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('6', '3', 'Vieux Carré', 'Este coctel se preparara en vaso mezclador. Si tenemos brandy pero no coñac, como es un poco más dulce y más expresivo, en vez de partes iguales de bourbon y brandy, pondríamos 4 y 2, para contrarrestar. Se añade hielo al vaso mezclador y se vierten todos los licores, el bitter y la angostura. Removemos bien con cuchara de cotel y lo servimos en un vaso ancho y bajo con hielo. Se hace un twist de naranj para aportar aromas frescos y se coloca un poco de romero, para dar aroma y contrastar los colores.', '3 cl de bourbon, 3 cl de coñac, 3cl de vermú, una cucharadita de Bénedictine, tres gotas de bitter Peychaud, dos gotas de angostura, naranja y romero para decorar y aromatizar');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('6', '4', 'Callos a la gallega', 'Limpieza de los callos

    Ponemos los garbanzos a remojo de un día para otro, no menos de 8 horas, para que se rehidraten.
    Ponemos a remojo también la uña de cerdo con su codillo. Una vez que le hayamos pedido a nuestro carnicero que nos la trocee, durante una noche.
    Cuando compremos la carne para los callos, pediremos también a nuestro carnicero que nos trocee la pata de ternera.
    Ya en casa dejaremos a remojo en agua con el zumo y las pieles de dos limones, la carne del estómago de ternera que habremos troceado y la pata desde la noche anterior.
    Esto facilitará el trabajo de limpieza de estas carnes. Aunque hoy en día se comercializan mucho más limpias que hace años. El zumo de limón nos ayudará en el proceso para que nos queden inmaculadas para cocinarlas.
    Después de tener a remojo los garbanzos, la uña y codillo de cerdo. También las carnes de estómago y pata de ternera desde la noche anterior, nos ponemos manos a la obra.
    Lavamos de nuevo muy bien el estómago y la pata de ternera, principalmente el estómago. Le dedicaremos cierto esmero a este proceso.
Preparación de los callos a la gallega

    En una olla rápida ponemos a cocer en agua fría el estómago troceado, la pata de ternera y la uña y codillo de cerdo, durante 5 o 6 minutos sin poner la olla en presión.
    Desechamos esta primera agua de cocción y volvemos a cubrir. Añadimos a la olla la cebolla troceada en dados, los dientes de ajo troceados, los pimentones picante y dulce, el comino y un punto de sal. Cocemos las carnes durante 15 minutos.
    Abrimos la olla enfriándola directamente bajo el grifo de agua fría.
    Añadimos los garbanzos, cerramos de nuevo la olla rápida y cocinamos los callos durante 30 minutos. Siempre hasta que veamos que los garbanzos y la carne están casi tiernos. Volvemos a abrir la cazuela enfriándola directamente bajo el grifo.
    Si optamos por emplear una cazuela tradicional, deberíamos cocer las carnes unos 50 minutos antes de añadir los garbanzos.
    Una vez que tengamos los garbanzos en la cazuela, los coceremos entre 1 hora y media y 2 horas comprobando que estén en su punto.
    Añadimos el chorizo en trocitos o rodajas. Continuamos la cocción 30 minutos más con la olla sin presión.
    Comprobamos el punto de cocción pudiendo aumentarlo o reducirlos en este último proceso según veamos.
', '1 kg. garbanzos, 1/3 estómago de ternera, 2 chorizos ahumados (mejor si son gallegos), 1 uña de cerdo con codillo en salazón, 1 pata de ternera, 1 cabeza de ajos, 1 cebolla grande, 2 limones, 1 cucharadita de comino molido, 1 cucharadita de pimentón dulce y otra de picante, Sal (al gusto de casa)');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('6', '5', 'Tortitas americanas Thermomix', 'Ponemos todos los ingredientes de las tortitas en el vaso y programamos 30 segundos a velocidad 4. Pasamos la masa de tortitas Thermomix a una jarrita o un biberón de cocina (como este) y dejamos reposar 30 minutos en la nevera.
En una plancha o sartén antiadherente con un trocito de mantequilla engrasamos la superficie.
Cuando la sartén esté bien caliente, vertemos una pequeña cantidad, aproximadamente 2 cucharadas soperas de masa.
Esperamos hasta que toda la superficie se llene de burbujitas, entonces con una lengua o espátula le damos la vuelta; dejamos que se dore por el otro lado, unos segundos y sacamos.
Repetimos la operación hasta que se nos acabe la mezcla. Vamos poniendo las tortitas en un plato una encima de otra y tapamos con papel aluminio para que se mantengan calientes.
Servimos las tortitas acompañadas con la guarnición que más nos guste', '2 huevos, 30 g de mantequilla pomada, 1 vaso (200 ml) de leche, 30 g de azúcar, 220 g de harina de trigo, 1/2 cucharadita de levadura química (tipo Royal), 1 trocito de mantequilla');

INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('7', '3', 'Mimosa de frambuesa', 'Hay que tener el cava o champagne muy frío para servir al momento de prepararlo. ponemos las frambuesas en una licuadora o procesador de alimentos por un minuto hasta que queden como puré. Vaciamos esto en cada copa de tipo flauta. Añadimos un poco de azúcar de caña líquida. Terminamos con el champagne o cava y mezclamos despacio. Servimos inmediatamente', '100g de frambuesas congeladas, 2 cucharadas de azucar de caña líquido, 1 botella de cava');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('7', '3', 'Dry Martini', 'Para elaborar este cóctel se necesitas un vaso mezclador y una copa Martini, que previamente habremos metido en el congelador. De las Muelas deposita la copa con suavidad en una bandeja de plata cubierta con un paño de hilo, añade una aceituna (manzanilla o verde sevillana son las adecuadas) y, a continuación, escancia sobre el vaso mezclador lleno de cubitos de hielo una copa de ginebra helada y dos golpes del vermut seco. Remueve todo ello suavemente durante 15 segundos con una cuchara, lo agita dos segundos más y lo sirve en la copa. Tras un twist o no de piel de limón se deja que los invitados tomen su copa de la bandeja. “Se deja que desvirguen la copa”, apunta De las Muelas', 'una copa de ginebra, dos golpes de vermut seco (preferiblemente Nolly Prat o Martini Extra Dry), un twist de limón (opcional)');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('7', '3', 'Daiquiri', 'Con ayuda del vaso medidor vertemos en la coctelera una parte de zumo de lima recién exprimido, el azúcar y dos partes de ron blanco (en este orden, pues siempre los “diluyentes” se colocan antes). Después, añadimos cuatro o cinco cubos de hielo –preferiblemente industrial, para evitar malos aromas de la nevera–. Tapamos y agitamos la coctelera durante 15 segundos, sirviendo el cóctel con ayuda del filtro de la propia coctelera o el colador en un vaso de cóctel', '50 ml de ron blanco, 25 ml de zumo de lima, 1 cucharilla de azúcar, hielo');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('7', '6', 'Bocadillo de ternera con salteado de pimiento, cebolla y mozzarella', 'Salpimentar y aderezar la carne con tomillo y orégano; reservar. Calentar un poco de aceite en una sartén y añadir la cebolla con una pizca de sal. Cocinar a fuego medio-bajo hasta que se caramelice al gusto. Añadir el pimiento y saltear a temperatura media hasta que esté tierno o dejándolo con un punto crujiente. Retirar. Cortar la porción de pan y abrir en dos mitades. Cocinar la carne a la plancha o parrilla procurando que quede al punto. Retirar. Abrir el pan y dorar en la misma parrilla. Presionar para compactarlo un poco. Montar el bocadillo con una base de tomate salpimentado, la carne, la mezcla de verduras y el queso. Dar un golpe de pimienta y añadir orégano al gusto. Cerrar y pasar por la parrilla de nuevo.', '1 cebolla dulce o blanca en juliana fina, 1 pimiento rojo en tiras, 2 filetes de ternera pequeños, 1 tomate en rama en rodajas, rodajas de mozzarella fresca, orégano, tomillo, pimienta negra, sal y aceite de oliva virgen extra, pan de chapata o similar.');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('7', '6', 'Bocadillo de tinga de pollo al chile chipotle', 'Sofreímos la cebolla y el tomate con aceite. Dejamos a fuego lento mientras en una olla tendremos la pechuga de pollo hirviendo por unos 20 minutos. Al terminar este tiempo retiramos el pollo del agua y la deshebramos. Agregamos el pollo a la sartén. Picamos el chile y lo añadimos. Sazonamos con el comino, sal y pimienta. Revolvemos bien todo y dejamos a fuego lento unos 10 a 12 minutos. Calentamos los panes miniatura, los cortamos en dos y rellenamos con la tinga.', '250 g de cebolla blanca en juliana, 1 tomate maduro en trozos, 1 pechuga de pollo, 4 panecillos tiernos, 1 chile chipotle en adobo, 2 g de comino molido, sal, pimienta negra y aceite de oliva virgen extra.');

INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('8', '3', 'Cóctel frutal', 'Mezclamos las uvas lavadas con el melocotón, el Cointreau y el cava. Revolvemos y dejamos reposar unos 30 minutos en refrigeración. Retiramos del refrigerador y añadimos ahora el tequilla, el azúcar de caña líquido y mucho hielo. Removemos bien para que todos los sabores se puedan integran mejor. Servimos directamente en vasos cortos tipo y con más hielo picado', '750ml de sidra, 20cl de tequila reposado, 10cl de Cointreau, una cucharada de azúcar de caña líquido, una taza de uvas negras, media taza de melocotón picado en almíbar y mucho hielo');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('8', '3', 'Cóctel de cava', 'Simplemente hay que colocar una flor por copa y servir el cava o champán directamente sobre ellas. En pocos instantes liberará su color y aroma al rehidratarse, y al terminar la bebida incluso podemos comerla, estará muy dulce', 'Flores de hibiscus deshidratadas o en almíbar, 1 botella de cava');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('8', '6', 'Bocadillo de gambas con wakame y sriracha', 'Limpiamos las gambas, retiramos el intestino y las cocinamos en la sartén con una cucharada de aceite de oliva y unas gotas de aceite de sésamo. Agregamos una cucharada sopera de sriracha y mezclamos bien salteando. Cuando veamos que las gambas toman un color rojo intenso, añadimos un chorreón de zumo de limón y salteamos otro minuto. Colocamos un poco de ensalada de wakame en la parte de abajo de cada pan. Repartimos las gambas en los dos bocadillos, colocándolas sobre la ensalada de algas. Terminamos rebañando la sartén con la parte de arriba de los panes. Después, colocamos unas cuantas hojas de cilantro fresco o perejil, y cerramos.', '12 colas de gambas o langostinos, 2 cucharadas de salsa sriracha o al gusto, zumo de limón, 2 panecillos tipo Viena, 2 cucharadas de ensalada de algas wakame, cilantro o perejil fresco, aceite de oliva virgen extra, aceite de sésamo (opcional), sal al gusto.');

INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('9', '3', 'Margarita', 'En primer lugar, debemos preparar las copas en la que vamos a servir el cóctel. Debemos pasar la lima por el borde de la copa y colocar esta boca abajo en un plato con sal, para lograr el mítico borde salino que caracteriza al cóctel. Una vez tengamos las copas listas, con ayuda del vaso medidor vertemos en la coctelera el zumo de lima recién exprimido, el tequila, y el triple seco (en este orden, pues siempre los “diluyentes” se colocan antes). Después, añadimos cuatro o cinco cubos de hielo. Tapamos y agitamos la coctelera durante 15 segundos, sirviendo el cóctel con ayuda del filtro de la propia coctelera o el colador', '75 ml de tequila, 25 ml de triple seco, 25 ml de zumo de lima, hielo, sal');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('9', '3', 'Mandarina Blast', 'Cortamos la cáscara de la mandarina y la ponemos a infusionar con el agua caliente por unos 30 minutos. Al cabo de este tiempo añadimos la rama de canela y el azúcar de caña líquido. Revolvemos muy bien y dejamos infusionar por otros 30 minutos más. Al cabo de esa primer hora, retiramos las cáscaras de mandarina de la infusión y la pasamos por el colador de ser necesario para retirar los eventuales trocitos de la piel de mandarina que se hayan podido desprender. Agregamos el mezcal y volvemos a mezclar muy bien. Servimos con mucho hielo. Las medidas son para una copa, y se pueden multiplicar según el número de invitados', '100 ml de mezcal, 1 mandarina, 175 ml de agua caliente, canela en rama, 15 ml de azúcar de caña líquido, hielo');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('9', '3', 'Manhattan', 'Para disfrutarlo como es debido, advierte De las Muelas, “este cóctel ha de ser transparente como un cristal y helado como un tempano”. Para lograr esto se deben servir los ingredientes en el vaso mezclador junto con abundante hielo. A continuación, remueve durante 15 segundos y sirve en una copa de cóctel. Como remate, decora con una guinda roja', '2/3 de whisky de centeno o bourbon, 1 golpe de angostura, 1/3 de vermú rojo');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('9', '6', 'Bocadillo de jamón cocido con dulce de membrillo, pera y queso Gruyère', 'Cortar el pan y abrir por la mitad. Tostar ligeramente en una sartén, plancha, horno o con la tostadora, añadiendo un poco de aceite. Mezclar la mayonesa con la mostaza y untar las dos mitades. Lavar y descorazonar la pera. Cortar en láminas finas, dejando la piel si no nos importa, y sumergir en un plato hondo con agua fría y hielo, para que se quede crujiente. Cortar el dulce de membrillo en lonchas y hacer lo mismo con el queso Gruyère, sin corteza. Montar el bocadillo alternando capas de ingredientes, secando bien la pera, y dando un golpe de pimienta negra sobre el queso. Añadir un chorrito de aceite de oliva virgen extra de buena calidad antes de cerrar el pan.', '1 barra de pan de buena calidad estilo rústico, 30 ml de mayonesa o yogur natural aderezado con limón y sal, 5 ml de mostaza de Dijon, dulce de membrillo, 1 pera ercolina o conferencia no muy madura, 2 lonchas generosas de jamón cocido artesano, 30 g de queso Gruyère, pimienta negra y aceite de oliva virgen extra.');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('9', '1', 'Tarta de cerveza negra Guinness, chocolate y crema de queso', 'Empezamos poniendo en un cazo al fuego la cerveza y la mantequilla troceada y, sin que llegue a hervir, las calentamos a fuego medio, hasta que la mantequilla se derrita completamente. Retiramos el cazo del fuego y lo reservamos.

En un bol tamizamos el cacao, el azúcar, la harina y el bicarbonato. Removemos con una cuchara hasta que esté todo bien mezclado. En otro bol ponemos la nata líquida, los huevos y la vainilla líquida y los batimos con unas varillas manuales.

Agregamos el contenido del cazo al bol con 140 ml de la nata (el resto es para la cobertura) y los mezclamos. Poco a poco vamos incorporando la mezcla de líquidos a los ingredientes secos, removiendo hasta conseguir una masa uniforme y sin grumos, bastante líquida.

Engrasamos un molde y ponemos en él esta mezcla, cociéndola a horno precalentado a 180ºC durante 50 minutos o hasta que pinchando con un palillo este salga limpio. Lo sacamos y lo dejamos enfriar.
Mientras, preparamos la crema. Empezando montando los 360 g restantes de nata. Después, mezclamos el queso y el azúcar con un batidor eléctrico, hasta conseguir una crema suave. Incorporamos la nata y lo mezclamos con movimientos suaves hasta conseguir una crema untuosa que repartimos sobre el bizcocho una vez frío.', 'Cerveza Guinness 250 ml, Mantequilla 250 g, Cacao en polvo 75 g, Azúcar 400 g, Nata líquida con 35% de materia grasa 500 ml, Huevo 2, Extracto de vainilla una cucharadita, Harina de repostería 250 g, Bicarbonato sódico dos cucharaditas y media, Queso crema 250 g, Azúcar glas 150 g');

INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('10', '3', 'Singapore Sling', 'Para hacer el cóctel, se vierten los ingredientes uno por uno en la coctelera, repleta de hielo, y se agita todo muy bien. La presentación debe hacerse en un vaso alto en el que no pueden faltar los hielos. Se puede adornar con una cereza y un trocito de piña', '3 cl de ginebra, 1,5 cl de licor de cereza, 0,75 cl de licor triple seco (Cointreau), 1 cl de granadina, 1,5 cl de zumo de limón y 12 cl de zumo de piña');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('10', '3', 'Blackberry Gin Fizz', 'Tan solo hay que triturar unas 5 moras frescas con dos cucharadas de azúcar y colar la mezcla. Esto asegurará el sabor dulce y afrutado de la bebida. Se añade una parte de ginebra y una de limón y se mezcla todo muy bien. Por último se suma el hielo y se echa la soda para llenar los vasos. Para decorar, se recomienda usar unas ramitas de albahaca o unas rodajas de limón', 'Ginebra , moras, zumo de limón, azúcar, soda y albahaca');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('10', '3', 'Mojito', 'Echamos dos cucharaditas de azúcar blanco en un vaso alto, a ser posible un poco más ancho que el de tubo, para poder remover bien el hielo. Después vertemos el zumo de lima, o exprimimos media lima troceada sobre el azúcar con la ayuda del mortero. Ahora, antes de echar la hierbabuena, podemos añadir la soda o sifón. Después colocamos una ramita de hierbabuena, removiendo con fuerza, pero sin triturar, para sacarle su aroma. Ya por último, vertemos el ron, añadimos el hielo, la pajita, una ramita decorativa y a disfrutar', '1 Parte de ron, 2 Partes de soda, 1 parte de zumo de lima, azúcar blanco y hierbabuena fresca');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('10', '1', 'Crema de chocolate y naranja con almendra crocante', 'Introducimos el chocolate picado en un recipiente hondo y le añadimos la ralladura de una de las naranjas. Reservamos. Calentamos la crème fraîche y la leche en un cacito, sin dejar que llegue a hervir.

Mezclamos las yemas con el azúcar y las agregamos al cacito con la mezcla anterior. Removemos para integrar. Cocemos a fuego medio hasta que espese, sin dejar que sobrepase los 80º C (para que no se corten las yemas).

Vertemos la crema sobre el chocolate y removemos para que se funda. Cuando obtengamos una mezcla homogénea añadimos un pellizco de sal y el aceite de oliva virgen extra. Removemos de nuevo hasta incorporar.

Repartimos la crema en seis vasitos y dejamos atemperar. Entonces los pasamos a la nevera y esperamos a que cojan cuerpo durante unas horas (mejor toda la noche). En el momento de servir espolvoreamos cada uno con almendra crocante y decoramos con tiras de piel de naranja.', 'Naranja 2, Chocolate negro picado 140 g, Crème fraîche (crema fresca) 240 g, Leche (mejor entera) 240 g, Yema de huevo 6, Azúcar 50 g, Sal 2 g, Aceite de oliva virgen extra 15 ml, Sal, Crocanti de almendras para servir 50 g');
INSERT INTO recetas (id_usuario, id_tipo, nombre, preparacion, ingredientes) VALUES ('10', '1', 'Tarta de queso y yogur con higos', 'Disponer en un recipiente la harina de repostería con el azúcar moreno o panela, la almendra molida, los copos de avena, una pizca de sal y un poco de ralladura fina del limón. Cortar la mantequilla fría en cubitos, añadir y mezclar con una batidora de varillas o, mejor, frotando con las manos hasta tener una textura cremosa homogénea, pegajosa.

Envolver en plástico film formando un disco y refrigerar, al menos 30 minutos. Mientras, precalentar el horno a 200ºC y engrasar un molde de tartas rizado de unos 20-22 cm de diámetro y dejar atemperar los ingredientes del relleno fuera de la nevera.

Estirar la masa entre dos capas de papel de horno antiadherente y cubrir el molde. Es una masa pegajosa y se pone blanda rápidamente si hace mucho calor, pero no tiene que quedar perfecta. Con ayuda del papel de horno y las manos, extender para ocupar todos los recovecos del molde y hornear en blanco 15 minutos (dejando una capa de papel y poniendo peso encima, como legumbres secas o arroz).

Retirar el papel y los pesos y comprobar que está firme y algo dorada; si estuviera muy blanca, hornear unos pocos minutos más. Retirar, bajar la potencia del horno a 160ºC sin aire y preparar el relleno.
Batir juntos los huevos, el queso crema, el yogur o queso batido, el azúcar, una cucharadita de zumo de limón y otra de su ralladura fina, la vainilla, otra pizca de sal y la maizena, hasta no tener grumos. Procurar que no salgan muchas burbujas o dar unos golpes suaves al bol contra la mesa para sacar y explotar las que haya.

Verter sobre la tarta cocida. Cortar los higos lavados (pelados opcionalmente) en cuartos y distribuir en el relleno al gusto. Hornear durante unos 40-45 minutos, o hasta que haya cuajado. Dejar enfriar un poco antes de refrigerar unas horas.', 'Mantequilla sin sal 125 g, Harina de repostería 100 g, Almendra molida 50 g, Azúcar moreno o panela 20 g, Copos de avena finos o más almendra 20 g, Sal (dos pizcas) 2 g, Huevo 3, Queso crema 300 g, Yogur griego (auténtico) natural desnatado o normal 250 g, Azúcar 85 g, Maizena 15 g, Esencia de vainilla (opcional) 2.5 ml, Limón mediano 1');